name: 'ewallet-system'

volumes:
  mysql-nodejs:
    external: true

services:
  db:
    container_name: mysql-service
    hostname: mysql-service
    image: mysql:8
    restart: unless-stopped
    volumes:
      - mysql-nodejs:/var/lib/mysql/data
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD="1!2@3#4$5%6^"
      - MYSQL_DATABASE=ewallet_system
  
  app:
    container_name: app-service
    hostname: app-service
    build:
      context: .
      dockerfile: nodejs.dockerfile
      no_cache: true
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./app/.env:/home/node/app/.env
      - ./app/prisma:/home/node/app/prisma
      - ./app/src:/home/node/app/src
      - ./app/tests:/home/node/app/tests
  