name: 'ewallet-system'

volumes:
  postgres-data:
    external: true
  # mysql-data:
  #   external: true
      
services:
  postgres:
    container_name: postgre-service
    hostname: postgre-service
    image: postgres:16
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=ewallet_system
  
  app:
    container_name: app-service
    hostname: app-service
    build:
      context: .
      dockerfile: nodejs.dockerfile
      no_cache: true
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./app/.env:/home/node/app/.env
      - ./app/prisma:/home/node/app/prisma
  